"""Cap the stack with a plain roof slab.

The `WEBSITE - Model` layer of BEEHOME GEOMETRIES.3dm has no roof in it. In
the original the roof is the `2` suffix on the export string, generated by
BEEHOME.gh at download time -- a storey run through Grasshopper with the
cavities left uncarved. Without Rhino that generator is out of reach, so this
writes the thing it would have produced: the same plan as the base plate, no
bores, no channels.

It is a stand-in and is labelled as one in the model index. What it fixes is
real, though: with nothing on top, every render ended on the open cavity
channels of the last storey, which is not how the object was ever shown.

    python3 tools/make_roof.py
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mesh_storeys import write_glb  # noqa: E402

OUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "viewer", "public", "models")

# Plan of the base plate, so the roof reads as its pair: the stack is book-ended
# by two plain slabs and the cavity storeys sit between them.
WIDTH, DEPTH, THICKNESS = 140.0, 160.0, 22.0


def box(width, depth, height):
    """A flat-shaded box, origin at the centre of its underside -- the same
    convention every storey in the model index uses."""
    x, y = width / 2, depth / 2
    corners = {
        "bottom": [(-x, -y, 0), (x, -y, 0), (x, y, 0), (-x, y, 0)],
        "top": [(-x, -y, height), (-x, y, height), (x, y, height), (x, -y, height)],
        "front": [(-x, -y, 0), (-x, -y, height), (x, -y, height), (x, -y, 0)],
        "back": [(x, y, 0), (x, y, height), (-x, y, height), (-x, y, 0)],
        "left": [(-x, y, 0), (-x, y, height), (-x, -y, height), (-x, -y, 0)],
        "right": [(x, -y, 0), (x, -y, height), (x, y, height), (x, y, 0)],
    }
    normals = {
        "bottom": (0, 0, -1), "top": (0, 0, 1),
        "front": (0, -1, 0), "back": (0, 1, 0),
        "left": (-1, 0, 0), "right": (1, 0, 0),
    }

    # Flat lists of floats, three per vertex: the glTF writer counts vertices
    # by dividing the length by three.
    positions, out_normals = [], []
    for face, quad in corners.items():
        for a, b, c in ((0, 1, 2), (0, 2, 3)):
            for i in (a, b, c):
                positions.extend(quad[i])
                out_normals.extend(normals[face])
    return positions, out_normals


def main():
    positions, normals = box(WIDTH, DEPTH, THICKNESS)
    path = os.path.join(OUT_DIR, "roof.glb")
    write_glb(path, positions, normals)

    index_path = os.path.join(OUT_DIR, "index.json")
    with open(index_path) as fh:
        index = json.load(fh)

    entry = {
        "name": "roof",
        "file": "models/roof.glb",
        "size_mm": [WIDTH, DEPTH, THICKNESS],
        "note": "stand-in for the Grasshopper roof variant; plain slab, no bores",
    }
    index["guides"] = [g for g in index["guides"] if g["name"] != "roof"] + [entry]
    with open(index_path, "w") as fh:
        json.dump(index, fh, indent=1)

    print(path, len(positions) // 3, "triangles")


if __name__ == "__main__":
    main()
